Lan = "CN"
"Setting" = "设置界面"
"Enable Dalamud log" = "使用卫月日志"
"Scan Hotbar" = "扫描热键栏"
"Scan Macro" = "扫描宏"
"Pathfinding Visual" = "寻路相关数据可视化"
"Clear" = "清除"
"User Tool" = "用户工具"
"Enable Debug log" = "启用Debug日志"
"Open log folder" = "打开日志文件夹"
"Input simulation level :" = "模拟输入等级 :"
"AntiAfk" = "防T(挂机操作用)"
"Lower UpdateInterval,Higher Cpu usage." = "Update间隔越低,插件表现越好,cpu消耗越高.有个i5就可以拉满"
"UpdateInterval (ms):" = "Update间隔 (ms): "
"PathfindingServerUrl:" = "寻路服务器Url:"
"QQ Group (CN): " = "QQ群:"
"Curr ACR:" = "当前ACR:"
"Dot blacklist" = "Dot黑名单"
"Hotkey" = "快捷键"
"Macro" = "宏"
"ACR Prefer" = "ACR偏好"
"TTK" = "目标濒死检测"
"General TTK Time" = "通用TTK机制检测时间"
"FinalBurst TTK Time" = "最终爆发TTK检测时间"
"Save Setting" = "保存设置"
"AutoReset" = "自动重置"
"Reload Triggerlines" = "重新加载时间轴"
"Force load" = "强制加载"
"Open Editor" = "打开时间轴编辑器"
"Avaliable triggerlines for Terr" = "当前场景可用时间轴"
"Open Triggerline Folder" = "打开时间轴文件夹"
"Import data from souma timeline" = "导入Souma时间轴"
"Convert" = "转换"
"Paste souma timeline here" = "将Souma时间轴粘贴到此处"
"Confirm" = "确认"
"Rename" = "重命名"
" Cast " = "秒 用 "
"Specify triggerline: (auto switch off): " = "指定时间轴(不自动切换) : "
"Clear and auto switch once" = "清除并自动切换一次"
"Load" = "指定加载"
"CastSpell" = "使用技能"
"DisableOtherGroup" = "关闭其他组"
"LockSpell" = "锁定技能"
"ReplayOpener" = "重新用起手"
"SelectTarget" = "切换目标"
"SetRotation" = "设置面向"
"SpellQueue" = "技能队列"
"SwitchAOE" = "切换AOE"
"SwitchBurst" = "切换爆发"
"SwitchFinalBurst" ="切换最终爆发"
"SwitchDOT" = "切换DOT"
"SwitchPull" = "切换自动攻击"
"UsePotion" = "使用爆发药"
"AfterBattleStart" = "战斗开始后多少秒"
"AfterOtherGroup" = "另一组触发后"
"Buff left time less than X(s)" = "buff小于多少秒"
"CheckSpellCD" = "检测技能CD"
"CountDownInOpener (ms)" = "起手倒计时剩余多少ms"
"EnemyCastSpell" = "敌人读条使用技能"
"TargetHpPct (by name/id)" = "目标血量百分比 (通过名字或者Id)"
"TargetHpPct (by targetType)" = "目标血量百分比 (通过类型)"
"EnemyIsLOS" = "敌人出现在视野中"
"EnemyTimeToKill (s)" = "敌人TTK (几秒内死亡)"
"ChatListener" = "聊天监控"
"In 'TargetHpPct (by targetType)',you cant set the targetType to Location/DefaultByCode/SpecifyTarget " = "在目标血量百分比 (通过类型)中,无法配置TargetType为Location/DefaultByCode/SpecifyTarget "
"MeleePosHelper:" = "身位指示器设置:"
"Flank:" = "侧面:"
"Behind:" = "背面:"
"Enable" = "启用"
"OnWeatherChange" = "天气变化"
"CurrWeatherId" = "当前天气Id"
"Ops: LeftClick to show the editor /RightClick to show the popup" = "左键选中以打开节点编辑UI,右键单击以打开二级菜单"
"Action" = "行为"
"Condition" = "条件"
"Delay[Sec]" = "延迟[秒]"
"MultiTimes" = "多次执行"
"Parallel" ="并行"
"Sequence" = "序列"
"Select" = "选择"
"Delete" = "删除"
"Up" = "上移"
"Down" = "下移"
"Copy" = "复制"
"Paste" = "粘贴"
"ExposedVars:" = "导出变量:"
"Curr Version: " = "当前版本:"
"Latest Version: " = "最新版本: "
"Curr version is the latest!" = "当前版本是最新版本!"
"Please login to the game first!" = "请先登录游戏!"
"Developer bypass" = "开发者免验证"
"Verify" = "验证"
"Please input your key!" = "请输入你的Key!"
"Auto login" = "自动登录"
"Error: " = "错误: "
"Please do not spread it actively, otherwise your activation code and subcode may be invalid!" = "请不要主动对外扩散，否则你的激活码和子码可能会失效!"
"Incompatible warning: " = "不兼容警告: "
"The following plugins are detected in the plugin list. To avoid compatibility issues, please make sure that the following plugins are disabled before verification!" = "检测到插件列表中存在以下插件，为避免产生兼容问题，请先确保已禁用以下插件再进行验证!"
"Clear dummy aggro" = "清除木人仇恨"
"AutoReset Setting" = "自动重置设置"
"True North" = "真北"
"Button Setting" = "按钮设置"
"Max Gcd Spell Count" = "Gcd内最大能力技数量"
"Gcd Queue Time" = "Gcd队列时间"
"Attack Range" = "攻击距离"
"Auto Interrupt" = "自动打断"
"Window Scale" = "窗口缩放"
"Melee Pos Helper" = "近战身位指示器"
"Auto Pull (in combat)" = "自动主动攻击"
"Auto Load Triggerline" = "自动加载时间轴"
"Enable Pantsu" = "激活底裤功能"
"Spell No Move" = "技能不位移"
"Olaf" = "奥拉夫"
"Strength" = "力量"
"Dexterity" = "巧力"
"Mind" = "头脑"
"Intelligence" = "智力"
"Lock Movement" = "移动锁定"
"Lock Movement Time" = "移动锁定时间"
"Use TTK" = "使用TTK"
"TTK Ignore Damage" = "TTK可忽略的最低伤害值"
"Unload Triggerline" = "卸载时间轴"
"Battle Time" = "战斗时间"
"Curr Triggerline" = "当前时间轴"
"None" = "无"